#!/bin/sh
pybabel extract -F babel.cfg -o translations/templates/LC_MESSAGES/messages.pot .
for __DIR in `ls translations`
do
  if [ "$__DIR" != "templates" ];
  then
    pybabel update -i translations/templates/LC_MESSAGES/messages.pot -d translations -l $__DIR
  fi
done
pybabel compile -f -d translations
