#!/bin/sh
pushd .
cd ../socialapi-pages
rm -rf jp-JP es-AR css js images index.html
wget -nH -erobots=off -p http://localhost:8888/index.html
wget -nH -erobots=off -p http://localhost:8888/sharePanel.html
wget -nH -erobots=off -p http://localhost:8888/redirect.html
for __LOCALE in cs de en-US es fr gl it ja nl pt-BR ru sl uk zh-TW
do
  rm -rf $__LOCALE
  wget -r -nH -erobots=off http://localhost:8888/$__LOCALE/activated/
  rm $__LOCALE/activated/index.html
  wget -r -nH -erobots=off http://localhost:8888/$__LOCALE/
  wget -nH -erobots=off -p http://localhost:8888/$__LOCALE/sharePanel.html
  git add -A --ignore-removal $__LOCALE
done

# old goal.com pages
wget -nH -erobots=off -p http://localhost:8888/id/goal.html
wget -nH -erobots=off -p http://localhost:8888/id/
wget -nH -erobots=off -p http://localhost:8888/es-AR/goal.html
wget -nH -erobots=off -p http://localhost:8888/es-AR/
wget -nH -erobots=off -p http://localhost:8888/es-ES/goal.html
wget -nH -erobots=off -p http://localhost:8888/es-ES/
git add -A --ignore-removal id es-AR es-ES
git add *.html

popd
